### ISSUE TITLE
Issue with Converting PDMX JSON to MusicXML

### ISSUE THREAD

**Issue by KdaiP** [pnlong/ExpressionNet#2]
Hi, thanks for your awesome work! I encountered an issue while trying to convert PDMX JSON files to MusicXML. The conversion doesn’t seem to work as expected.

I use the code below to convert:

```
for idx, json_file in enumerate(json_files):
    music = pdmx.load(json_file)
    music.write_midi(f'pdmx_test_{idx}.midi')
    music.write_musicxml(f'pdmx_test_{idx}.musicxml')
    
    score = music.to_music21()
    score.write('musicxml', f'pdmx_test_{idx}_21.musicxml')
```

And we get the result:
Convert to midi:
![image](https://github.com/user-attachments/assets/3e161b34-9052-4592-9873-9dae98fc4fdd)
![image](https://github.com/user-attachments/assets/c2a3438d-2aef-467b-9209-dfc5e8493598)

Convert to music21/musicxml(muspy use music21 as backend to save musicxml file, so it get the same result):
![image](https://github.com/user-attachments/assets/f895b8b5-55e8-4e5a-aef9-5a9331964b91)
![image](https://github.com/user-attachments/assets/816eef9c-6d23-47be-b840-a781e2b77ba1)

It seems that there are some problem on converting to musicxml. I’ve also attached some example files for reference. Could you give some guidance on how to resolve this issue? Thank you for your help!

[debug.zip](https://github.com/user-attachments/files/17807785/debug.zip)

**Comment by pnlong** [comment]
The functionality that writes to MusicXML is not perfect (I spent most of my time focusing on writing to MIDI and WAV formats). I am currently working on improving this part of `MusicRender` -- it should be ready in about a week.

**Comment by pnlong** [comment]
I've pushed an updated version of the output to MusicXML function. A lot of stuff should be fixed (notes and annotations should be in the right place). However, by the nature of reading music into a universal object, some information gets lost and cannot be recovered. Where this affects the output to MusicXML is that information necessary for recreating drum tracks (which notes map to which drums) is lost. For this reason, drum tracks are all placed on a single pitch; however, the rhythms are still correct. Everything else should work OK though.

Let me know if you find any other problems. However, the output to MusicXML function can only be so good, as some information always is lost when using the `MusicRender` object, so the outputted MusicXML file can never be a perfect recreation after the original is loaded as `MusicRender`.

**Comment by pnlong** [comment]
Actually, I am working on improving the drum output. Should be done by today.

**Comment by pnlong** [comment]
I have done my best to fix the MusicXML output. Like I said, in converting to a universal `MusicRender` object, some information is bound to get lost. Though I have fixed the drum output to the best of my ability, and it now works pretty well in most cases.

However, we use the `music21` package as a backend for converting `MusicRender` objects to MusicXML, which has its fair share of bugs. In fact, even after we convert a `MusicRender` object to a `music21` object, and output that to MusicXML, there are still quite a few issues, so the code actually goes into the XML files themselves and tweaks some stuff.

I think this will conclude my work on the output to MusicXML function for now, as any further improvements would require me to essentially ditch the `music21` backend and write my own `MusicRender` direct to MusicXML framework, which would be a herculean effort that goes beyond the scope of this project (and into the scope of another one on which I am currently working). I will close this issue here.
